import type { Metadata } from 'next';
import { space_grotesk } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Cloudbase Paralotnie',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={space_grotesk.className}>{children}</body>
    </html>
  );
}
