import type { Metadata } from 'next';
import { Space_Grotesk, Teko } from 'next/font/google';
import './globals.css';

export const space_grotesk = Space_Grotesk({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable: '--font-space',
});
export const teko = Teko({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--font-teko',
});

export const metadata: Metadata = {
  title: 'Cloudbase Paralotnie',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${space_grotesk.variable} ${teko.variable}`}>{children}</body>
    </html>
  );
}
